# Inherit from Hound default configuration so we can perform the same
# checks locally.
inherit_from: ./.rubocop_hound.yml

AllCops:
  TargetRubyVersion: 2.1

# Use double quotes only for interpolation.
Style/StringLiterals:
  EnforcedStyle: single_quotes

# Place dots at the beginning of multiline method calls.
Layout/DotPosition:
  EnforcedStyle: leading

# Allow using {} when chaining methods
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

# The default of 80 characters is a little to narrow.
Metrics/LineLength:
  Max: 100

# Only place spaces inside blocks written with braces.
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Do not warn about missing magic comment
Style/FrozenStringLiteralComment:
  Enabled: false

# Allow `json.(:attribute)`
Style/LambdaCall:
  Enabled: false

# Ignore long RSpec describe blocks
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature']