module PageflowScrolled
  # Describe the places where the configurations of an entry can
  # reference files.
  #
  # @api private
  class EntryFileReferenceLocations
    def initialize(entry_config, content_elements, include_unused: false)
      @entry_config = entry_config
      @content_elements = content_elements
      @include_unused = include_unused
    end

    def content_element_locations
      content_element_type_names.each_with_object({}) do |type_name, result|
        schema = schemas.find(model: 'contentElement', type_name:)

        if schema
          result[type_name] = locations.for(schema)
        else
          log_missing_schema(type_name)
        end
      end
    end

    def section_locations
      locations_for(model: 'section')
    end

    def entry_locations
      locations_for(model: 'entry')
    end

    private

    def locations_for(model:)
      schema = schemas.find(model:)

      unless schema
        raise("Missing configuration schema for #{model}. Configuration schemas are " \
              'generated by the JavaScript build or by running ' \
              'yarn build-configuration-schemas inside the scrolled package.')
      end

      locations.for(schema)
    end

    # Content elements of any type can be added in the editor without
    # reloading the seed.
    def content_element_type_names
      if @include_unused
        schemas.type_names(model: 'contentElement')
      else
        @content_elements.map(&:type_name).uniq
      end
    end

    def log_missing_schema(type_name)
      return unless @entry_config.features.enabled?('file_rights_from_references')

      Rails.logger.warn("Missing configuration schema for content element type '#{type_name}'")
    end

    def schemas
      @schemas ||= @entry_config.configuration_schemas
    end

    def locations
      @locations ||= FileReferenceLocations.new(schemas)
    end
  end
end
