module PageflowScrolled
  class ContentElement < Pageflow::ApplicationRecord
    include Pageflow::SerializedConfiguration
    include Pageflow::AutoGeneratedPermaId

    belongs_to :section

    def self.all_for_revision(revision)
      joins(section: {chapter: {storyline: :revision}})
        .where(pageflow_scrolled_storylines: {revision_id: revision})
    end
  end
end
