module PageflowScrolled
  class Section < Pageflow::ApplicationRecord
    POSITION_ORDER = [
      'pageflow_scrolled_storylines.position ASC',
      'pageflow_scrolled_chapters.position ASC',
      'pageflow_scrolled_sections.position ASC'
    ].join(',')

    include Pageflow::SerializedConfiguration
    include Pageflow::AutoGeneratedPermaId
    include Pageflow::NestedRevisionComponent

    belongs_to :chapter
    has_many :content_elements,
             -> { order('pageflow_scrolled_content_elements.position ASC') },
             dependent: :destroy,
             inverse_of: :section

    nested_revision_components :content_elements

    def self.all_for_revision(revision)
      joins(chapter: {storyline: :revision})
        .where(pageflow_scrolled_storylines: {revision_id: revision})
        .order(POSITION_ORDER)
    end
  end
end
