common: &common
  adapter: mysql2
  encoding: utf8mb4
  username: <%= ENV.fetch('PAGEFLOW_DB_USER', 'root') %>
  password: <%= ENV.fetch('PAGEFLOW_DB_PASSWORD', '') %>
  pool: 5
<% if ENV['PAGEFLOW_DB_HOST'].present? %>
  host: <%= ENV['PAGEFLOW_DB_HOST'] %>
  port: <%= ENV.fetch('PAGEFLOW_DB_PORT', '3306') %>
<% elsif File.socket?('/var/run/mysqld/mysqld.sock') %>
  socket: /var/run/mysqld/mysqld.sock
<% elsif File.socket?('/tmp/mysql.sock') %>
  socket: /tmp/mysql.sock
<% else %>
  host: localhost
  port: 3306
<% end %>

development:
  <<: *common
  database: development

test:
  <<: *common
  database: test
