module Pageflow
  # Add a +perma_id+ attribute of type integer.
  # The perma_id is automatically generated on create
  # and remains unchanged throughout the models lifecycle.
  module AutoGeneratedPermaId
    extend ActiveSupport::Concern

    included do
      before_save :ensure_perma_id
    end

    def ensure_perma_id
      return if perma_id.present?

      entry = entry_for_auto_generated_perma_id

      self.perma_id =
        if entry.new_record?
          # No other process can see the entry yet, so there is nothing
          # to lock.
          entry.increment(:perma_id_counter).perma_id_counter
        else
          entry.with_lock do
            entry.increment!(:perma_id_counter)
            entry.perma_id_counter
          end
        end
    end

    def entry_for_auto_generated_perma_id
      raise NotImplementedError,
            "#{self.class.name} must implement #entry_for_auto_generated_perma_id"
    end
  end
end
