module Pageflow
  class TestNestedRevisionComponent < ActiveRecord::Base
    self.table_name = :test_nested_revision_components

    include NestedRevisionComponent
    include AutoGeneratedPermaId

    belongs_to :parent, class_name: 'TestCompositeRevisionComponent'
    has_many :items, class_name: 'TestDeeplyNestedRevisionComponent', foreign_key: :parent_id

    nested_revision_components :items

    def entry_for_auto_generated_perma_id
      parent.revision.entry
    end
  end
end
