module Pageflow
  class TestDeeplyNestedRevisionComponent < ActiveRecord::Base
    self.table_name = :test_deeply_nested_revision_components

    include NestedRevisionComponent
    include AutoGeneratedPermaId

    belongs_to :parent, class_name: 'TestNestedRevisionComponent'

    def entry_for_auto_generated_perma_id
      parent.entry_for_auto_generated_perma_id
    end
  end
end
