module Pageflow
  # RevisionComponent represents a model that is attached to the revision
  # mechanism of Pageflow.
  #
  # In order to be used as a revision component, a model is required
  # to have an integer field `perma_id` and a `revision_id` foreign
  # key.
  module RevisionComponent
    extend ActiveSupport::Concern

    include AutoGeneratedPermaId
    include NestedRevisionComponent::Container

    def entry_for_auto_generated_perma_id
      revision.entry
    end

    included do
      belongs_to :revision, class_name: 'Pageflow::Revision', touch: true
    end

    def copy_to(revision)
      record = dup
      record.revision = revision
      record.save!

      copy_nested_revision_component_to(record)
    end

    module ClassMethods # rubocop:todo Style/Documentation
      def all_for_revision(revision)
        where(revision_id: revision.id)
      end

      def from_perma_ids(revision, perma_ids)
        return [] if revision.blank? || perma_ids.blank?

        perma_ids.map { |perma_id|
          find_by_revision_id_and_perma_id(revision.id, perma_id)
        }.compact
      end
    end
  end
end
