module.exports = {
  module: {
    rules: [
      {
        // Nested in oneOf to keep the rule free of a top level `type`
        // property. Host application webpack configs generated by the
        // install generator use `mergeWithRules` to match rules by
        // `type` and would otherwise replace the `test` below.
        oneOf: [
          {
            // Emit the WebAssembly module of the dotLottie player as
            // asset, so that it does not have to be loaded from a CDN.
            test: /\.wasm$/,
            type: 'asset/resource'
          }
        ]
      }
    ]
  },
  resolve: {
    alias: {
      // By default Video.js now includes the http-streaming
      // plugin. To reduce bundle size on mobile devices, we load it
      // dynamically in src/frontend/dash only if HLS is not natively
      // supported by the browser.
      'video.js$': 'video.js/core.es.js'
    },
    fallback: {
      // Silently ignore minimatch trying to load Node built-in module.
      'path': false
    }
  },
  entry: {
    'pageflow-scrolled/contentElements/tikTokEmbed-frontend': {
      import: [
        'pageflow-scrolled/contentElements/tikTokEmbed-frontend',
        'pageflow-scrolled/contentElements/tikTokEmbed-frontend.css'
      ]
    },
    'pageflow-scrolled/contentElements/twitterEmbed-frontend': {
      import: [
        'pageflow-scrolled/contentElements/twitterEmbed-frontend',
        'pageflow-scrolled/contentElements/twitterEmbed-frontend.css'
      ]
    },
    'pageflow-scrolled/contentElements/hotspots-frontend': {
      import: [
        'pageflow-scrolled/contentElements/hotspots-frontend',
        'pageflow-scrolled/contentElements/hotspots-frontend.css'
      ]
    },
    'pageflow-scrolled/contentElements/socialEmbed-frontend': {
      import: [
        'pageflow-scrolled/contentElements/socialEmbed-frontend',
        'pageflow-scrolled/contentElements/socialEmbed-frontend.css'
      ]
    },
    'pageflow-scrolled/contentElements/videoEmbed-frontend': {
      import: [
        'pageflow-scrolled/contentElements/videoEmbed-frontend',
        'pageflow-scrolled/contentElements/videoEmbed-frontend.css'
      ]
    },
    'pageflow-scrolled/contentElements/inlineBeforeAfter-frontend': {
      import: [
        'pageflow-scrolled/contentElements/inlineBeforeAfter-frontend',
        'pageflow-scrolled/contentElements/inlineBeforeAfter-frontend.css'
      ]
    },
    'pageflow-scrolled/contentElements/lottieAnimation-frontend': {
      import: [
        'pageflow-scrolled/contentElements/lottieAnimation-frontend',
        'pageflow-scrolled/contentElements/lottieAnimation-frontend.css'
      ]
    },
    'pageflow-scrolled/widgets/defaultNavigation': {
      import: [
        'pageflow-scrolled/widgets/defaultNavigation',
        'pageflow-scrolled/widgets/defaultNavigation.css'
      ]
    },
    'pageflow-scrolled/widgets/consentBar': {
      import: [
        'pageflow-scrolled/widgets/consentBar',
        'pageflow-scrolled/widgets/consentBar.css'
      ]
    },
    'pageflow-scrolled/widgets/excursionSheet': {
      import: [
        'pageflow-scrolled/widgets/excursionSheet',
        'pageflow-scrolled/widgets/excursionSheet.css'
      ]
    },
    'pageflow-scrolled/widgets/mainStorylineSheet': {
      import: [
        'pageflow-scrolled/widgets/mainStorylineSheet',
        'pageflow-scrolled/widgets/mainStorylineSheet.css'
      ]
    },
    'pageflow-scrolled/widgets/iconInlineFileRights': {
      import: [
        'pageflow-scrolled/widgets/iconInlineFileRights',
        'pageflow-scrolled/widgets/iconInlineFileRights.css'
      ]
    },
    'pageflow-scrolled/widgets/textInlineFileRights': {
      import: [
        'pageflow-scrolled/widgets/textInlineFileRights',
        'pageflow-scrolled/widgets/textInlineFileRights.css'
      ]
    },
    'pageflow-scrolled/widgets/iconScrollIndicator': {
      import: [
        'pageflow-scrolled/widgets/iconScrollIndicator',
        'pageflow-scrolled/widgets/iconScrollIndicator.css'
      ]
    },
    'pageflow-scrolled-frontend-inlineEditing': {
      import: [
        'pageflow-scrolled/frontend/inlineEditing.css',
        'pageflow-scrolled/review.css'
      ]
    },
    'pageflow-scrolled-frontend-commenting': {
      import: [
        'pageflow-scrolled/frontend/commenting.css',
        'pageflow-scrolled/review.css'
      ]
    }
  }
};
