import {useEntryStateConfig} from "./EntryStateProvider";

/**
 * Returns data generated by a Ruby lambda registered server
 * side via `config.additional_frontend_seed_data.register`.
 *
 * @example
 *
 * const data = useAdditionalSeedData('someSeed');
 */
export function useAdditionalSeedData(name) {
  const config = useEntryStateConfig();

  if (!config.additionalSeedData[name]) {
    throw new Error(`Could not find additional seed data with name '${name}'.`)
  }

  return config.additionalSeedData[name];
}
